# Generated by Django 5.0.4 on 2024-04-18 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='Место выполнения')),
                ('date', models.DateField(verbose_name='Дата выполнения')),
                ('time', models.TimeField(verbose_name='Время выполнения')),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('is_enjoyed', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('frequency', models.PositiveIntegerField(default=1, verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вознаграждение')),
                ('lasting', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
